name: PrisonCore
version: '${version}'
main: us.dxtrus.prisoncore.PrisonCore
api-version: '1.20'
depend: [DxtrusCommons, FastAsyncWorldEdit]
softdepend: [PlaceholderAPI, DexterousScoreboard, HuskSync]