SET DEFAULT_STORAGE_ENGINE = INNODB;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS `ranks` (`id` INT NOT NULL AUTO_INCREMENT , `uuid` TEXT NOT NULL , `rank` TEXT NOT NULL DEFAULT 'default' , `expires_at` BIGINT NOT NULL )
CREATE TABLE IF NOT EXISTS `statistics` (`id` INT NOT NULL AUTO_INCREMENT , `uuid` TEXT NOT NULL , `tokens` TEXT NOT NULL DEFAULT '0' , `gems` TEXT NOT NULL DEFAULT '0' , `blocks_broken` TEXT NOT NULL DEFAULT '0')