SET DEFAULT_STORAGE_ENGINE = INNODB;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS `ranks` (`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, `uuid` TEXT NOT NULL , `rank` TEXT NOT NULL DEFAULT 'default' , `expires_at` BIGINT NOT NULL );
CREATE TABLE IF NOT EXISTS `statistics` (`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY , `uuid` VARCHAR(255) NOT NULL , `tokens` VARCHAR(255) NOT NULL DEFAULT '0' , `gems` VARCHAR(255) NOT NULL DEFAULT '0' , `blocks_broken` VARCHAR(255) NOT NULL DEFAULT '0' );